require_relative 'prox_gem'

source 'https://rubygems.org'

# Because PROX_GEM_MODE == off, looks in whatever gem sources are specified (ie: https://rubygems.org)
# See ../set-env-vars.sh, and ./set-env-vars.sh
prox_gem 'some_gem'
